@startuml create-diagram
actor User 
User -> PostService: create post
alt success 
    PostResource <-- PostService: success 
    User <-- PostResource: success 
else failure 
    PostResource <-- PostService: failure 
    User <-- PostResource: failure
end
@enduml